### ISSUE TITLE
Move crud utils from DalaiLama repo

### ISSUE THREAD

**Issue by vaibhavmule** [Mindgreppers/epicsearch#20]
- [ ] One config file for 1. client connection Paramenters to ES servers 2. timeouts/batchSizes for collect queries 3. basePath for contexts and schema

- [ ] Take a base folder pa

- [ ] Allow es.get.deep() -> A context param: wherein context tells which fields to get from the document and which fields to join. This can be a relative path below the basePath supplied to es while initializing it.
- [ ] Allow es.update.deep() -> using js=-Two extra update params. 1. force: true/false, 2. update //Object as per js-object-updater API 

- [ ] es.index.deep()

- [ ] es.delete.deep()

**Comment by dhope21** [comment]
1.
